## A

In [88]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from tqdm import tqdm
import matplotlib.pyplot as plt
from time import time
from sklearn.linear_model import Lasso

In [89]:
def MSE(X, weights, bias , Y):
    pred = np.dot(X, weights)+bias
    error = 0
    for i in range(len(Y)):
        error += (pred[i]-Y[i])**2
    return error/len(Y)/2

In [90]:
def MAE(X, weights, bias , Y):
    pred = np.dot(X, weights)+bias
    error = 0
    for i in range(len(Y)):
        error += np.abs(pred[i]-Y[i])
    return error/len(Y)

In [91]:
weights = np.array([[-0.15], [0.6]])
bias = -59.5
X = np.array([[41,138],[42,153],[37,151],[46,133]])
Y = np.array([[37.99],[47.34],[44.38],[28.17]])

In [92]:
print(MSE(X, weights, bias, Y))

[182.802875]


In [93]:
print(MAE(X, weights, bias, Y))

[18.945]


## B

In [94]:
learning_rate = 0.1

In [95]:
np.dot(X[0,:], weights) + bias

array([17.15])

In [96]:
X[0]

array([ 41, 138])

first update

In [97]:
prediction = np.dot(X[0], weights) + bias
prediction

array([17.15])

In [98]:
dev_weights =  2 * ((prediction - Y[0]) * X[0]).reshape((-1,1))
dev_bias = 2 * (prediction - Y[0])
print(f'delta bias: {dev_bias} delta weights: {dev_weights.reshape((-1))}')

delta bias: [-41.68] delta weights: [-1708.88 -5751.84]


In [99]:
weights -= learning_rate * dev_weights
bias -= learning_rate * dev_bias
print(f'After first update we have bias: {bias} weights: {weights.reshape((-1))}')

After first update we have bias: [-55.332] weights: [170.738 575.784]


second update

In [100]:
prediction = np.dot(X[1], weights) + bias
prediction

array([95210.616])

In [101]:
dev_weights =  2 * ((prediction - Y[1]) * X[1]).reshape((-1,1))
dev_bias = 2 * (prediction - Y[1])
print(f'delta bias: {dev_bias} delta weights: {dev_weights.reshape((-1))}')

delta bias: [190326.552] delta weights: [ 7993715.18400001 29119962.45600002]


In [102]:
weights -= learning_rate * dev_weights
bias -= learning_rate * dev_bias
print(f'After second update we have bias: {bias} weights: {weights.reshape((-1))}')

After second update we have bias: [-19087.9872] weights: [ -799200.7804 -2911420.4616]


third update

In [103]:
prediction = np.dot(X[2], weights) + bias
prediction

array([-4.69214007e+08])

In [104]:
dev_weights =  2 * ((prediction - Y[2]) * X[2]).reshape((-1,1))
dev_bias = 2 * (prediction - Y[2])
print(f'delta bias: {dev_bias} delta weights: {dev_weights.reshape((-1))}')

delta bias: [-9.38428102e+08] delta weights: [-3.47218398e+10 -1.41702643e+11]


In [105]:
weights -= learning_rate * dev_weights
bias -= learning_rate * dev_bias
print(f'After third update we have bias: {bias} weights: {weights.reshape((-1))}')

After third update we have bias: [93823722.20152007] weights: [3.47138478e+09 1.41673529e+10]


forth update

In [106]:
prediction = np.dot(X[3], weights) + bias
prediction

array([2.04403546e+12])

In [107]:
dev_weights =  2 * ((prediction - Y[3]) * X[3]).reshape((-1,1))
dev_bias = 2 * (prediction - Y[3])
print(f'delta bias: {dev_bias} delta weights: {dev_weights.reshape((-1))}')

delta bias: [4.08807092e+12] delta weights: [1.88051262e+14 5.43713433e+14]


In [108]:
weights -= learning_rate * dev_weights
bias -= learning_rate * dev_bias
print(f'After forth update we have bias: {bias} weights: {weights.reshape((-1))}')

After forth update we have bias: [-4.08713269e+11] weights: [-1.88016549e+13 -5.43571759e+13]


MSE

In [109]:
print(MSE(X, weights, bias, Y))

[3.70218393e+31]


## C

In [110]:
weights = np.array([[-0.15], [0.6]])
bias = -59.5

In [111]:
prediction = np.dot(X, weights) + bias
prediction

array([[17.15],
       [26.  ],
       [25.55],
       [13.4 ]])

In [112]:
dev_weights =  (np.sum((prediction - Y) * X, axis=0)/len(X)).reshape(-1,1)
dev_bias = (np.sum((prediction - Y), axis=0)/len(X)).reshape(-1,1)
print(f'delta bias: {dev_bias} delta weights: {dev_weights.reshape((-1))}')

delta bias: [[-18.945]] delta weights: [ -781.7125 -2737.17  ]


In [113]:
weights -= learning_rate * dev_weights
bias -= learning_rate * dev_bias
print(f'After one update in GD we have bias: {bias} weights: {weights.reshape((-1))}')

After one update in GD we have bias: [[-57.6055]] weights: [ 78.02125 274.317  ]


MSE

In [114]:
print(MSE(X, weights, bias, Y))

[9.08587593e+08]
